<h2 id="customizer"><?php _e( '' ); ?></h2>
<?php
	get_customizer_component(
		array(
			'site-identity',
			'general-settings',
			'logo-favicon',
			'breadcrumbs',
			'social-links',
			'page-layout',
			'maintenance',
			'skins-style',
			'color-scheme',
			'color',
			'typography',
			'header',
			'background-image',
			'menu-locations',
			'sidebar',
			'mailchimp',
			'widgets',
			'footer',
			'ads-management',
			'blog-settings',
			'woocommerce-options',
			'google-analytics',
			'static-front-page',
			'the-events-calendar',
			'404',
            'custom-css',
			'export-import',
			'styleswitcher',

		)
	);
?>
