<article id="video-slider">
    <div id="toc-video-slider" class="toc-id"></div>
    <h3 id="video-slider"><?php _e( 'Video Slider' ); ?></h3>

<p><?php _e( 'Power builder makes it possible to create video sliders and video galleries with custom thumbnails and play buttons.' ); ?>
</p>

<h4><?php _e( 'Module Options:' ); ?></h4>
	<ul class="marked-list">
		<li>
            <dl class="inline-term">
                <dt><?php _e( 'admin label ' ); ?></dt>
                <dd>
    				<?php _e( 'this will change the label of the video in the builder for easy identification;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt><?php _e( 'video MP4/URL' ); ?></dt>
                <dd>
    				<?php _e( 'upload your desired video in <strong>.MP4</strong> format, or type in the url to the video you would like to display;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> <?php _e( 'video webm' ); ?></dt>
                <dd>
                   <?php _e( 'upload the <strong>.WEBM</strong> version of your video here. All uploaded videos should be in both <strong>.MP4 .WEBM</strong> formats to ensure maximum compatibility in all browsers;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt><?php _e( 'image overlay url' ); ?></dt>
                <dd>
                   <?php _e( 'upload your desired image, or type in the url to the image you would like to display over your video. You can also generate a still image from your video;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> <?php _e( 'display image overlays on main video' ); ?></dt>
                <dd>
                  <?php _e( 'this option will cover the player UI on the main video. This image can either be uploaded in each video setting or auto-generated by Divi;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> <?php _e( 'arrows' ); ?></dt>
                <dd>
                   <?php _e( 'this setting will turn on and off the navigation arrows;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt><?php _e( ' slider controls' ); ?></dt>
                <dd>
                   <?php _e( 'this setting will let you choose to use the thumbnail track controls below the slider or dot navigation at the bottom of the slider;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt><?php _e( 'disable on' ); ?> </dt>
                <dd>
    				<?php _e( 'this will disable the module on selected devices;' ); ?>
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt><?php _e( 'admin label' ); ?></dt>
                <dd>
                    <?php _e( 'this will change the label of the module in the builder for easy identification.' ); ?>
                </dd>
            </dl>
        </li>
	</ul>

    </article>
